version: '3.9'

services:

  user_crud_api:
    container_name: user_crud_api
    image: luizcornelli/user_crud_api:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://user_crud_db:5432/user_crud_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - user_crud_db

  user_crud_db:
    container_name: user_crud_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_crud_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
